### ISSUE TITLE
Error adding event: No access, refresh token or API key is set.

### ISSUE THREAD

**Issue by Meistercoach83** [scott-mccartney/google-calendar-cloud-function#1]
Hey! I get the error in the title when I try to execute your function.. What am I doing wrong?

**Comment by Nycticorax** [comment]
If you have no error during execution then it's probably of problem of state. Please make sure:
- that your variables are named correctly;
- that your JSON credentials file is structured correctly (i.e. 
`
{
    web: { ... },
    refresh_token: '...'
}`
- that you have correctly set the google auth playground to obtain your refresh token
- that your refresh token is up to date

**Comment by scott-mccartney** [comment]
@Meistercoach83 Be sure that you have added the credentials.json file as detailed in the README of this repo. The fields inside of that will contain a refresh token that I did not want to include in a public repo. You should follow the steps in the README and the linked Medium article to generate your own, private credentials.json file.
